name: ci

on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: run grumphp check
        run: make grumphp